# Generated by Django 5.2.1 on 2026-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_is_featured_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/', verbose_name='Ícone Personalizado (Imagem)'),
        ),
    ]
